### ISSUE TITLE
GreatExpectationsBigQueryOperator  - tuple index out of range error

### ISSUE THREAD

**Issue by marktanios7** [astronomer/airflow-provider-great-expectations#28]
Hello team,

I’m receiving the below error when I try to use GreatExpectationsBigQueryOperator

```
[2021-05-20 00:23:39,025] {validation_operators.py:405} ERROR - Error running action with name update_data_docs
Traceback (most recent call last)
  File "/opt/python3.6/lib/python3.6/site-packages/great_expectations/validation_operators/validation_operators.py", line 392, in _run_action
    payload=batch_actions_results
  File "/opt/python3.6/lib/python3.6/site-packages/great_expectations/checkpoint/actions.py", line 62, in ru
    **kwargs
  File "/opt/python3.6/lib/python3.6/site-packages/great_expectations/checkpoint/actions.py", line 939, in _ru
    validation_result_suite_identifier.expectation_suite_identifier
  File "/opt/python3.6/lib/python3.6/site-packages/great_expectations/core/usage_statistics/usage_statistics.py", line 262, in usage_statistics_wrapped_metho
    result = func(*args, **kwargs
  File "/opt/python3.6/lib/python3.6/site-packages/great_expectations/data_context/data_context.py", line 2304, in build_data_doc
    resource_identifiers, build_index=build_inde
  File "/opt/python3.6/lib/python3.6/site-packages/great_expectations/render/renderer/site_builder.py", line 293, in buil
    site_section_builder.build(resource_identifiers=resource_identifiers
  File "/opt/python3.6/lib/python3.6/site-packages/great_expectations/render/renderer/site_builder.py", line 388, in buil
    source_store_keys = self.source_store.list_keys(
  File "/opt/python3.6/lib/python3.6/site-packages/great_expectations/data_context/store/store.py", line 142, in list_key
    return [self.tuple_to_key(key) for key in keys_without_store_backend_id
  File "/opt/python3.6/lib/python3.6/site-packages/great_expectations/data_context/store/store.py", line 142, in <listcomp
    return [self.tuple_to_key(key) for key in keys_without_store_backend_id
  File "/opt/python3.6/lib/python3.6/site-packages/great_expectations/data_context/store/store.py", line 110, in tuple_to_ke
    return self._key_class.from_tuple(tuple_
  File "/opt/python3.6/lib/python3.6/site-packages/great_expectations/data_context/types/resource_identifiers.py", line 164, in from_tupl
    RunIdentifier.from_tuple((tuple_[-3], tuple_[-2]))
IndexError: tuple index out of rang
```

Here is my airflow task:

```
validate_output = GreatExpectationsBigQueryOperator(
    task_id='validate_output',
    gcp_project='<project_id>',
    #data_context=DC,
    gcs_bucket='<my_bucket_id>',
    gcs_datadocs_prefix='dags/playground/test_great_expectations/great_expectations',
    gcs_expectations_prefix='dags/playground/test_great_expectations/great_expectations/expectations',
    gcs_validations_prefix='dags/playground/test_great_expectations/great_expectations',
    expectation_suite_name='test_new_suite',
    bq_dataset_name='data_platform_staging',
    email_to='mark.tanios@talabat.com',
    send_alert_email=False,
    bigquery_conn_id='bigquery-greatexpectations',
    table='project_id.test_dataset.test_table',
    dag=dag
)
```

I’m using the latest *great-expectations* & *airflow-provider-great-expectations* dependencies.
I'm using Version : **1.10.14+composer**.

Thanks in advance!

**Comment by Faith-des** [comment]
I also interesting in answer. I have the same issue.
Maybe some update?

**Comment by denimalpaca** [comment]
Closing this as that version of the operator is no longer supported.
