### ISSUE TITLE
TypeError: can't pickle _thread.lock objects when cleaning

### ISSUE THREAD

**Issue by Casyfill** [astronomer/airflow-provider-great-expectations#5]
This is most likely an issue with airflow itself (we use 1.10.9), but we didn't have any similar issue with it before - on clearing GE operator, whole system goes kabum with this log:
```
Node: airflow-airflow-web-6f4fbbfc58-cnx4j
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/utils.py", line 290, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/utils.py", line 337, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/www/views.py", line 1296, in clear
    include_upstream=upstream)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dag.py", line 1211, in sub_dag
    for t in regex_match + also_include}
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dag.py", line 1211, in <dictcomp>
    for t in regex_match + also_include}
  File "/usr/local/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 681, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.lock objects
```

**Comment by edgarrmondragon** [comment]
We're on Airflow 1.10.13 and running into the same issue when trying to clear a `GreatExpectationsOperator` task.

**Comment by edgarrmondragon** [comment]
@Casyfill Oh I think I just found a solution :sweat_smile:. Threads seem to be used to send usage statistics so I disabled them in `great_expectations.yml`:

```yaml
anonymous_usage_statistics:
  enabled: false
```

**Comment by Casyfill** [comment]
Thanks @edgarrmondragon , that makes a lot of sense.
Perhaps still makes sense to turn this off automatically (or flash a warning) by default as part of the operator

**Comment by edgarrmondragon** [comment]
> Perhaps still makes sense to turn this off automatically (or flash a warning) by default as part of the operator

That would be reasonable as the true solution.

**Comment by Casyfill** [comment]
2 cents - it is obviously dependent on your deployment, but apparently, if you remove `data_context_id` (which I assumed to be unused given `enabled:false`) from the expectations yaml, it will attempt to override this YAML upon initialization. To avoid that (which does not make sense in airflow, and is forbidden by our settings), just get this line back, while keeping `enabled:false`

**Comment by spbail** [comment]
Thanks for helping triage this! Obviously this isn't an ideal solution form our perspective since we'd like to keep usage stats turned on if possible, but I'm glad there's at least a workaround. I'll tag this for review and maybe we can come up with a permanent fix.

**Comment by scoyne2** [comment]
On `airflow-provider-great-expectations==0.0.5` and `great-expectations==0.13.9` I too get error `can't pickle _thread.lock objects` when attempting to clear the GE Task using the below. 
(I am using Astronomer with Airflow 1.10.7

```
anonymous_usage_statistics:
  enabled: false
```

If I downgrade to `airflow-provider-great-expectations==0.0.4` and `great-expectations==0.13.7` I do not see this issue (except when attempting to use a Postgres MetricStore
